### ISSUE TITLE
help with reading a cell in a worksheet inside a quip

### ISSUE THREAD

**Issue by unixengineer** [dreamorosi/quip-spreadsheet#5]
I am tying to use the example, but it looks like it is incomplete. Do we need the quipclient module too?

**Comment by dreamorosi** [comment]
You are right, the example is incomplete, you have to import the `QuipClient` class as well.

```py
from quip_spreadsheet.quip import QuipClient

# Create the client, the values of Access Token & Base URL are stored in variables
quip = QuipClient(QUIP_ACCESS_TOKEN, QUIP_BASE_URL)
# Search the thread with specific name, limit result to 1
threads = quip.search_threads(THREAD_NAME, count=1)
# Store to a variable the first spreadsheet result
spreadsheet = threads.spreadsheets[0]
# Load its content
spreadsheet.load_content()
# Get a specific page of a spreadsheet
page = spreadsheet.get_named_page("Sheet1")
# Get a specific row from a page
row = page.get_nth_row(pointer)
# Get cells content from a row
cells = row.get_row_cells_content(include_index=False)
```

I'll update the README file as soon as I can, thanks for pointing this out.

**Comment by unixengineer** [comment]
Thanks. I did make the same change, but the QuipClient is not able to authenticate with quip (I use my org URL, but its all the same anyway). So, looks like there may be some issue with auth as well.

**Comment by dreamorosi** [comment]
Maybe you could try to share the error you're getting so I can see if I can help.
